swagger: '2.0'

info:
  version: "1.0.0"
  title: ACME Delivery service backend API
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

schemes: [ https ]
host: "backend.acme-company.site"
basePath: "/"

paths:
  /account/login:
    post:
      summary: "Authenticate user with login name and password."
      tags:
      - account
      consumes:
      - 'application/x-www-form-urlencoded'
      parameters:
      - name: 'login'
        in: formData
        type: string
      - name: 'password'
        in: formData
        type: string
      responses:
        '200':
          description: "User succesfully logged in."
          headers:
            Authorization:
              type: string
              description: |
                Authorization header with an API key. Browser will resend this
                header upon next request automatically.

  /account/logout:
    post:
      summary: "Log out current user."
      tags:
      - account
      responses:
        '200':
          description: "Current user succesfully logged out of system."
        '400':
          description: "User not logged in."
  /account/info:
    get:
      summary: "Get information about current user."
      tags:
      - account
      security:
      - api_key: []
      produces:
      - 'application/json'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '400':
          description: "User not logged in."

definitions:
  User:
    type: object
    required:
    - user_id
    - user_location
    - email
    - contact
    properties:
      user_id:
        type: integer
      user_location:
        type: string
      email:
        type: string
        format: email
      contact:
        $ref: '#/definitions/Contact'

  Contact:
    type: object
    required:
    - phone_number
    properties:
      address:
        type: string
      phone_number:
        type: string
      additional_info:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      position:
        type: string
      company:
        type: string

securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header

tags:
- name: "account"
  description: |
    Methods related to account/session management.